//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Putarina.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class praca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public praca()
        {
            this.usuario = new HashSet<usuario>();
        }
    
        public int id_praca { get; set; }
        public string cidade { get; set; }
        public string localizacao { get; set; }
        public int qtd_catracas { get; set; }
        public double preco_moto { get; set; }
        public double preco_carro_passeio { get; set; }
        public double preco_caminhao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuario> usuario { get; set; }
    }
}
