//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Putarina.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class registro_veiculo
    {
        public int id_veiculo { get; set; }
        public int id_usuario { get; set; }
        public System.DateTime horario { get; set; }
        public double preco_pago { get; set; }
        public string forma_pagamento { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual veiculo veiculo { get; set; }
    }
}
