//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Putarina.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.registro_veiculo = new HashSet<registro_veiculo>();
        }
    
        public int id_usuario { get; set; }
        public string nome { get; set; }
        public bool ativo { get; set; }
        public string nickusuario { get; set; }
        public System.DateTime data_nascimento { get; set; }
        public string senha { get; set; }
        public int catraca { get; set; }
        public int id_praca { get; set; }
        public string tipo { get; set; }
    
        public virtual praca praca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<registro_veiculo> registro_veiculo { get; set; }
    }
}
